### ISSUE TITLE
Cannot set the uncertainty after declaring a Measurement

### ISSUE THREAD

**Issue by ryanmartinneutrino** [Queens-Physics/qexpy#40]
Ex:
x = q.Measurement([1,2,3,4,5,6])
x.std = 0.5 # does not work
x.std(0.6) #does not work
x._std = 0.5 #does not work...

Presumably this is true for the mean as well...

**Comment by ryanmartinneutrino** [comment]
Good point, I forget what the context here was. Perhaps this should be done with an @property method, and warn the user that they are over-writing a pre-calculated uncertainty. I think it makes sense to be able to change the uncertainty in such a measurement, for example, to add in a systematic uncertainty:
```
x = q.Measurement([1,2,3,4,5,6])
x.std = math.sqrt(x.std**2+0.5**2)
```
although it will make sense to call this "error" instead of std.

**Comment by astralcai** [comment]
Good point. The change of uncertainty can be justified, so I will add that to my refactor. However, I don't think people should be allowed to change the value of the measurement. If they do, it should override the original list of raw measurements, since the value should just be the mean of that list of values, or else the repeated measurements would simply mean nothing

**Comment by ryanmartinneutrino** [comment]
In the above scenario, yes, it would not make sense to use a set of measurements and then overwrite the mean/central value. However, I could see a use case where one instantiates a measurement object with default values for central value and error (mean and std) of, say, 0, and then sets them later in the code by directly accessing the mean and std properties. For example, one may write a code where all variables are declared at the top, then values read in and set from a file. So it would get tricky to keep track of whether a user should be allowed to overwrite mean and std in general. Thus, I think the user should be allowed to overwrite them. 
Also, we should see if we can name mean and std better (std -> error, but mean -> central_value seem unwieldy)

**Comment by astralcai** [comment]
I don't see why a user would instantiate an empty object. They can declare a variable if they want but why would they instantiate it without any data? Another thing is that in my implementation, repeated measurement is a sub-class of measurement. Users are free to change the value and error of regular measurement (I named it MeasuredValue so that the wrapper method can still be called Measurement), however if they try to change the value of a RepeatedlyMeasuredValue object, they will get a warning, and the original array of measurements will be overridden, and the object will be casted to a general MeasuredValue object

**Comment by astralcai** [comment]
I think this is accounted for in the new version
